### ISSUE TITLE
Do initial sandbox deploy of Cumulus

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#87] opened 2023-01-19 15:27 UTC
-Get familiar with getting into the NGAP and the CBA environment
-Meet with Chuck to get initial input on deploying Cumulus (starting points)
-Attempt a cloud sandbox deploy - follow trouble shooting guide and document anything new that comes up

Parent Task: https://github.com/NASA-IMPACT/csdap-cumulus/issues/86

**Comment by chuckwondo** [comment] 2023-01-19 23:10
Duplicate of #92

**Closed by chuckwondo** 2023-01-19 23:10 UTC
